version: '3.8'

services:
  my-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
    depends_on:
      - my-postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
